### ISSUE TITLE
Improve email text

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/aragon#16]
Currently, the email will contain a predefined text, set during the creation of the connection.
It will be better to put some info from the event that triggers the connection.
We could either:
1. Hardcode a simple text with a link to the trigger either on aragon or simply on etherscan
2. Let the user enter its own text with a templating system
3. Create a predefined template with important data from the trigger. But as triggers contain different data, it will be really hard to have something nice and complete

**Comment by blackinno** [comment]
@NicolasMahe Could we use `js-function` service to combine and pass data to email service or other services? 

example: 

```yml
- type: task
  instanceHash: ${process.env.ETHEREUM_HASH}
  taskKey: decodeLog
  inputs:
    eventAbi: ${JSON.stringify(eventAbi)}
    address: {key: address}
    data: {key: data}
    topics: {key: topics}
    logIndex: {key: logIndex}
    transactionHash: {key: transactionHash}
    transactionIndex: {key: transactionIndex}
    blockHash: {key: blockHash}
    blockNumber: {key: blockNumber}
- type: task
   instance:
      src: https://github.com/liteflow-services/js-function
   taskKey: execute
   inputs:
      code: >
        module.export = value => (`${INPUT_TEXT_FROM_USER}, Transaction Hash : https://rinkeby.etherscan.io/tx/${value.transactionHash}`)
      inputs:
         decodedData: {key: decodedData}
         address: {key: address}
         eventSignature: {key: eventSignature}
         data: {key: data}
         topics: {key: topics}
         logIndex: {key: logIndex}
         transactionHash: {key: transactionHash}
         transactionIndex: {key: transactionIndex}
         blockHash: {key: blockHash}
         blockNumber: {key: blockNumber}
- type: task
  instanceHash: ${instanceHash}
  taskKey: send
  inputs:
    from: 'notification@mesg.com'
    to: ${data.to}
    subject: ${data.subject}
    text: {key: result}
```
